### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Ghazigq** [qiyongzhong0/rt-thread-qboot#1]
我觉得可以改进一个地方，将qbt_jump_to_app函数加上__weak并去掉static，防止出现app地址不在片内flash的情况（例如STM32H750，app在spi flash中），此时由用户自己定义该函数

**Comment by qiyongzhong0** [comment]
是的，在计划的v1.10版本开始，将qbt_jump_to_app函数改为week属性，在外部增加多个qboot_xxxx.c模块，用于实现不同内核芯片移植和扩展，模块主要功能就是qbt_jump_to_app函数针对不同芯片的实现。

**Comment by qiyongzhong0** [comment]
@Ghazigq 根据您的建议，现已增加qboot_stm32.c模块，模块内定义了宏QBOOT_APP_RUN_IN_QSPI_FLASH，以支持从外部QSPI flash运行应用程序，目前只是增加了一个框架，还没有加入代码实现，因我手上没有STM32H7的板子，没法测试验证，所以冒昧地征询您下！能否帮忙加入功能实现并进行测试验证。冒昧之处，万请见谅！多谢！多谢！

**Comment by Ghazigq** [comment]
> @Ghazigq 根据您的建议，现已增加qboot_stm32.c模块，模块内定义了宏QBOOT_APP_RUN_IN_QSPI_FLASH，以支持从外部QSPI flash运行应用程序，目前只是增加了一个框架，还没有加入代码实现，因我手上没有STM32H7的板子，没法测试验证，所以冒昧地征询您下！能否帮忙加入功能实现并进行测试验证。冒昧之处，万请见谅！多谢！多谢！

我现在板子上的qspi sfud还有问题，不能擦除某些块，还没解决呢

**Comment by qiyongzhong0** [comment]
这个是你的提问吗？ https://club.rt-thread.org/ask/question/425484.html

**Comment by Ghazigq** [comment]
> @Ghazigq这个是你的提问吗？[https: ](https://club.rt-thread.org/ask/question/425484.html)//club.rt-thread.org/ask/question/425484.html[](https://club.rt-thread.org/ask/question/425484.html)

是的，我该好好找找问题了0.0

**Comment by Ghazigq** [comment]
需要我怎么帮你测试 我现在用qbootV1.0.0版本已经可以正常使用了

**Comment by qiyongzhong0** [comment]
你好！多谢你能够帮忙！
你将qboot版本切换到latest，在qboot/src文件夹下有个qboot_stm32.c，这个文件是针对STM32系列芯片的应用跳转功能模块，打开模块中QBOOT_APP_RUN_IN_QSPI_FLASH宏定义，完善qbt_qspi_flash_init和qbt_jump_to_app函数并测试通过就可以了。
片外flash中运行代码，我没搞过，不太懂，全靠你了！



齐永忠
电话：15810366850
北京国电通网络技术有限公司
北京市北京市昌平区陈家营西路4号院1号楼 嘉铭奥森产业园西塔6层 
邮政编码：100000
 
发件人： Ghazigq
发送时间： 2020-09-14 14:46
收件人： qiyongzhong0/rt-thread-qboot
抄送： 齐永忠; State change
主题： Re: [qiyongzhong0/rt-thread-qboot] 建议 (#1)
需要我怎么帮你测试 我现在用qbootV1.0.0版本已经可以正常使用了

**Comment by Ghazigq** [comment]
> 你好！多谢你能够帮忙！ 你将qboot版本切换到latest，在qboot/src文件夹下有个qboot_stm32.c，这个文件是针对STM32系列芯片的应用跳转功能模块，打开模块中QBOOT_APP_RUN_IN_QSPI_FLASH宏定义，完善qbt_qspi_flash_init和qbt_jump_to_app函数并测试通过就可以了。 片外flash中运行代码，我没搞过，不太懂，全靠你了！ 齐永忠 电话：15810366850 北京国电通网络技术有限公司 北京市北京市昌平区陈家营西路4号院1号楼 嘉铭奥森产业园西塔6层 邮政编码：100000 发件人： Ghazigq 发送时间： 2020-09-14 14:46 收件人： qiyongzhong0/rt-thread-qboot 抄送： 齐永忠; State change 主题： Re: [qiyongzhong0/rt-thread-qboot] 建议 (#1) 需要我怎么帮你测试 我现在用qbootV1.0.0版本已经可以正常使用了 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

好的 等我消息

**Comment by Ghazigq** [comment]
`#define QBOOT_QSPI_FLASH_DEVICE_NAME "norspi"
static int nor_flash_memory_mapped_mode(struct rt_qspi_device * device)
{
    QSPI_CommandTypeDef      s_command;
    QSPI_MemoryMappedTypeDef s_mem_mapped_cfg;

    /* Configure the command for the read instruction */
    s_command.InstructionMode   = QSPI_INSTRUCTION_1_LINE;
    s_command.Instruction       = 0xEB;
    s_command.AddressMode       = QSPI_ADDRESS_4_LINES;
    s_command.AddressSize       = QSPI_ADDRESS_24_BITS;
    s_command.AlternateByteMode = QSPI_ALTERNATE_BYTES_4_LINES;
    s_command.AlternateBytes    = 0x00;
    s_command.AlternateBytesSize= QSPI_ALTERNATE_BYTES_8_BITS;
    s_command.DataMode          = QSPI_DATA_4_LINES;
    s_command.DummyCycles       = 4;
    s_command.DdrMode           = QSPI_DDR_MODE_DISABLE;
    s_command.DdrHoldHalfCycle  = QSPI_DDR_HHC_ANALOG_DELAY;
    s_command.SIOOMode          = QSPI_SIOO_INST_EVERY_CMD;

    /* Configure the memory mapped mode */
    s_mem_mapped_cfg.TimeOutActivation = QSPI_TIMEOUT_COUNTER_ENABLE;
    s_mem_mapped_cfg.TimeOutPeriod     = 1;

    if (HAL_QSPI_MemoryMapped((QSPI_HandleTypeDef *)(device->parent.bus->parent.user_data), &s_command, &s_mem_mapped_cfg) != HAL_OK)
    {
        rt_kprintf("memory mapped mode failed\n");
        return RT_ERROR;
    }
    else
        return RT_EOK;
}

void qbt_jump_to_app(void)
{
    typedef void (*app_func_t)(void);
    app_func_t app_func;
    u32 stk_addr = 0, reset_handler = 0;

    struct rt_qspi_device * device = (struct rt_qspi_device *)rt_device_find(QBOOT_QSPI_FLASH_DEVICE_NAME);

    if(device != RT_NULL)
    {
        rt_uint8_t send[4] = {0x03, 0x00, 0x00, 0x00};
        rt_uint8_t recv[8] = {0};

        rt_qspi_send_then_recv(device, send, sizeof(send), recv, sizeof(recv));
        stk_addr        = recv[0] | recv[1] << 8 | recv[2] << 16 | recv[3] << 24;
        reset_handler   = recv[4] | recv[5] << 8 | recv[6] << 16 | recv[7] << 24;

        LOG_D("SP:\t\t0x%08X",sp);
        LOG_D("RESET_HANDLE:\t0x%08X",reset_handler);

        stk_addr &= 0x2FF00000;
        if(((reset_handler & 0xff000000) != QSPI_BASE) ||
           (stk_addr != 0x20000000 && stk_addr != 0x24000000 && stk_addr != 0x30000000 && stk_addr != 0x38000000))
        {
            LOG_E("No legitimate application.");
            return;
        }

        if(nor_flash_memory_mapped_mode(device) == RT_EOK)
        {
          rt_kprintf("Jump to application running ... \n");
          __disable_irq();
#if (__MPU_PRESENT == 1)
          HAL_MPU_Disable();
#endif
          SCB_DisableICache();
          SCB_DisableDCache();
          __set_CONTROL(0);
          __set_MSP(stk_addr);
          app_func = (app_func_t) (*(__IO uint32_t*) (QSPI_BASE + 4));
          app_func();

          LOG_E("Qboot jump to application fail.");
        }
        return;
    }
    return;
}`
qbt_qspi_flash_init被我删掉了，配置增加一个QBOOT_QSPI_FLASH_DEVICE_NAME就可以了

**Comment by qiyongzhong0** [comment]
多谢你的支持，我会在代码修改记录中加入你的署名！具体署名写Ghaziqq吗？
另外，我有几个方面疑问，向你请教：

1. qspi flash映射地址之后是否就可以按照片内flash的方式直接读了呢？
2. 在跳到app运行前，外设和时钟没有恢复到复位状态，会否在app中初始化设备时引发异常。
3. 你代码中直接取flash开头数据做为app开始，有没有不把app放在flash开头的位置的使用情况呢？
4. 是否对所有恢复复位状态，qspi就没法工作了，所以不能对flash的spi接口初始化，相应的时钟也不能改变？这样boot和app就形成了一定的绑定关系了。
5. 是否可能如此实现：首先恢复外设、时钟以及中断配置到复位状态，然后配置spi时钟、引脚、映射地址空间，最后再跳到app地址运行。

以上是我的几点疑问和想法，你帮参详参详！！！



齐永忠
电话：15810366850
北京国电通网络技术有限公司
北京市北京市昌平区陈家营西路4号院1号楼 嘉铭奥森产业园西塔6层 
邮政编码：100000
 
发件人： Ghazigq
发送时间： 2020-09-14 15:52
收件人： qiyongzhong0/rt-thread-qboot
抄送： 齐永忠; State change
主题： Re: [qiyongzhong0/rt-thread-qboot] 建议 (#1)
`#define QBOOT_QSPI_FLASH_DEVICE_NAME "norspi"
static int nor_flash_memory_mapped_mode(struct rt_qspi_device * device)
{
QSPI_CommandTypeDef s_command;
QSPI_MemoryMappedTypeDef s_mem_mapped_cfg;
/* Configure the command for the read instruction */
s_command.InstructionMode   = QSPI_INSTRUCTION_1_LINE;
s_command.Instruction       = 0xEB;
s_command.AddressMode       = QSPI_ADDRESS_4_LINES;
s_command.AddressSize       = QSPI_ADDRESS_24_BITS;
s_command.AlternateByteMode = QSPI_ALTERNATE_BYTES_4_LINES;
s_command.AlternateBytes    = 0x00;
s_command.AlternateBytesSize= QSPI_ALTERNATE_BYTES_8_BITS;
s_command.DataMode          = QSPI_DATA_4_LINES;
s_command.DummyCycles       = 4;
s_command.DdrMode           = QSPI_DDR_MODE_DISABLE;
s_command.DdrHoldHalfCycle  = QSPI_DDR_HHC_ANALOG_DELAY;
s_command.SIOOMode          = QSPI_SIOO_INST_EVERY_CMD;
/* Configure the memory mapped mode */
s_mem_mapped_cfg.TimeOutActivation = QSPI_TIMEOUT_COUNTER_ENABLE;
s_mem_mapped_cfg.TimeOutPeriod     = 1;
if (HAL_QSPI_MemoryMapped((QSPI_HandleTypeDef *)(device->parent.bus->parent.user_data), &s_command, &s_mem_mapped_cfg) != HAL_OK)
{
    rt_kprintf("memory mapped mode failed\n");
    return RT_ERROR;
}
else
    return RT_EOK;

}
void qbt_jump_to_app(void)
{
typedef void (*app_func_t)(void);
app_func_t app_func;
u32 stk_addr = 0, reset_handler = 0;
struct rt_qspi_device * device = (struct rt_qspi_device *)rt_device_find(QBOOT_QSPI_FLASH_DEVICE_NAME);
if(device != RT_NULL)
{
    rt_uint8_t send[4] = {0x03, 0x00, 0x00, 0x00};
    rt_uint8_t recv[8] = {0};
    rt_qspi_send_then_recv(device, send, sizeof(send), recv, sizeof(recv));
    stk_addr        = recv[0] | recv[1] << 8 | recv[2] << 16 | recv[3] << 24;
    reset_handler   = recv[4] | recv[5] << 8 | recv[6] << 16 | recv[7] << 24;
    LOG_D("SP:\t\t0x%08X",sp);
    LOG_D("RESET_HANDLE:\t0x%08X",reset_handler);
    stk_addr &= 0x2FF00000;
    if(((reset_handler & 0xff000000) != QSPI_BASE) ||
       (stk_addr != 0x20000000 && stk_addr != 0x24000000 && stk_addr != 0x30000000 && stk_addr != 0x38000000))
    {
        LOG_E("No legitimate application.");
        return;
    }
    if(nor_flash_memory_mapped_mode(device) == RT_EOK)
    {
      rt_kprintf("Jump to application running ... \n");
      __disable_irq();

#if (__MPU_PRESENT == 1)
HAL_MPU_Disable();
#endif
SCB_DisableICache();
SCB_DisableDCache();
__set_CONTROL(0);
__set_MSP(stk_addr);
app_func = (app_func_t) ((__IO uint32_t) (QSPI_BASE + 4));
app_func();
      LOG_E("Qboot jump to application fail.");
    }
    return;
}
return;

}`
qbt_qspi_flash_init被我删掉了，配置增加一个QBOOT_QSPI_FLASH_DEVICE_NAME就可以了
―
