### ISSUE TITLE
命令行工具缺少加密参数

### ISSUE THREAD

**Issue by 209jkjkjk** [qiyongzhong0/rt-thread-qboot#10]
未能找到 "加密算法"，"加密密钥"，"加密IV"相关参数

对应GUI工具的config.ini，CryptType，CryptKey，CryptIV

**Comment by 209jkjkjk** [comment]
救救孩子

**Comment by qiyongzhong0** [comment]
命令行工具没做加密这块的功能.

**Comment by qiyongzhong0** [comment]
使用加密功能的话只能使用QBootPackager_V1.05

**Comment by 209jkjkjk** [comment]
收到，感谢回复

**Comment by 209jkjkjk** [comment]
命令行工具能提供源代码吗

**Comment by 209jkjkjk** [comment]
打包工具（命令行或GUI）能提供源代码吗

**Comment by 209jkjkjk** [comment]
没事了，因为是兼容rtthreadOTA 可以用官方工具rt_ota_packaging_tool_cli。虽然头部会有点区别，但是影响不大
