### ISSUE TITLE
qbt_release_sign_write 写入不成功问题

### ISSUE THREAD

**Issue by Rbb666** [qiyongzhong0/rt-thread-qboot#12]
当OTA结束后Qboot会调用qbt_release_sign_write 向download分区的最后写入0x5555AAAA，但写入前没有先擦除，会导致写入失败，如下图：
![image](https://github.com/user-attachments/assets/29730422-543f-4474-ab55-22c9ea19594f)

解决办法：
写入前先擦除下
![1722170550320](https://github.com/user-attachments/assets/191c0cf0-620c-433e-b62e-d396a753accc)

**Comment by qiyongzhong0** [comment]
此问题已通过增加固件包尺寸方式加以解决。
