### ISSUE TITLE
采用加密算法后的Bug

### ISSUE THREAD

**Issue by sddnuaa** [qiyongzhong0/rt-thread-qboot#2]
在采用加密算法后更新固件，如果程序打包时密钥不准确，会出现app分区被擦除的情况，建议在更新固件前检查download分区加密前固件的CRC是否准确，然后再执行更新固件的操作。 @qiyongzhong0

**Comment by qiyongzhong0** [comment]
是的，确实存在此问题。组件设计时也考虑过此问题，当时的想法是用户管理密钥，固件打包后会验证固件包正确性，所以对固件加密密钥合法性未进行验证。多谢你的反馈，会对此加以完善！

**Comment by qiyongzhong0** [comment]
@sddnuaa 你的建议已采纳，现已加入在更新固件前检查app的crc功能， 可以下载latest版本使用了。

**Comment by sddnuaa** [comment]
看到了，谢谢，但是在RT-Thread Studio软件包里没有v1.02，lastet版本里也没有这个功能，那边是不是也可以更新一下 @qiyongzhong0

**Comment by qiyongzhong0** [comment]
Studio总是从镜像地址下载，镜像自动更新有一天的延迟，所以你下载到的latest版本里没有，今天应该就有了，如果没有你可以从我这里下载后手动复制过去。

**Comment by sddnuaa** [comment]
芯片为stm32f103RE，开启QBOOT_USING_APP_CHECK，#define QBOOT_BUF_SIZE  256，固件采用默认的AES加密，Gzip压缩，校验通过，但是升级进度一直在00%，排查
static int qbt_dest_part_write(fal_partition_t part, u32 pos, u8 *decmprs_buf, u8 *cmprs_buf, u32 *p_cmprs_len, int cmprs_type)
decomp_len = qbt_gzip_decompress(decmprs_buf + gzip_remain_len, QBOOT_BUF_SIZE - gzip_remain_len);
decomp_len 返回值一直为零，取消QBOOT_USING_APP_CHECK，程序能升级正常，是我哪边没设置对吗？ @qiyongzhong0

**Comment by qiyongzhong0** [comment]
#### `#define QBOOT_BUF_SIZE                  4096//must is 4096`
#### 注意宏定义后面的注释！哈哈哈哈！

**Comment by sddnuaa** [comment]
在不加密的情况下，不是4096也正常，现在改成4096测试，结果如下：如果使用QBOOT_USING_QUICKLZ压缩方式，程序正常解密解压，但是如果QBOOT_USING_GZIP，qbt_app_crc_cal中，qbt_gzip_decompress返回值decomp_len = -4，
[E/Qboot] Qboot app crc check fail. decompress error.
[E/Qboot] Qboot firmware check fail. firmware app check fail.
感觉像内存不足引起的。如果QBOOT_BUF_SIZE改成1024，crc校验通过，write那边decomp_len=0，程序写入失败。 @qiyongzhong0

**Comment by qiyongzhong0** [comment]
#### 可能是内存不够的原因，看了zlib的readme中有如下说明：

> 注意，压缩文件需要大约 270 k 内存，如果内存不够会出现压缩失败的情况。
> 解压文件大约需要 18 k 内存占用。

**Comment by sddnuaa** [comment]
找到一直失败的原因了，小内存也可以用的，主要gzip解压完毕后需要调用inflateEnd(&qbt_strm)释放一下资源 @qiyongzhong0

**Comment by qiyongzhong0** [comment]
收到



---原始邮件---
发件人: "sddnuaa"<notifications@github.com&gt;
发送时间: 2020年9月17日(周四) 下午5:55
收件人: "qiyongzhong0/rt-thread-qboot"<rt-thread-qboot@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"齐永忠"<917768104@qq.com&gt;;
主题: Re: [qiyongzhong0/rt-thread-qboot] 采用加密算法后的Bug (#2)




 
找到一直失败的原因了，小内存也可以用的，主要gzip解压完毕后需要调用inflateEnd(&amp;qbt_strm)释放一下资源 @qiyongzhong0

**Comment by qiyongzhong0** [comment]
已修复gzip二次解压失败bug，你能帮我测一下吗？可以下载v1.03或latest版本进行测试。
@sddnuaa

**Comment by sddnuaa** [comment]
1、测试下来没有问题，但是QBOOT_BUF_SIZE我改成2048了，4096的时候还是失败的，inflate(&qbt_strm, Z_NO_FLUSH) 返回值是Z_MEM_ERROR，估计是内存不足的原因。
2、gzip解压内存占用还是挺大的，实际将近占用40K了，下面QBOOT_BUF_SIZE=2048时内存占用的测试结果
解压前内存占用情况：
total memory: 53632
used memory : 9028
maximum allocated memory: 13276

解压后内存占用情况：
total memory: 53632
used memory : 9028
maximum allocated memory: 48940

@qiyongzhong0

**Comment by qiyongzhong0** [comment]
好的，谢谢你！我可以发布v1.03版本了。
