### ISSUE TITLE
qbt_release_from_part 判断

### ISSUE THREAD

**Issue by HikerPan** [qiyongzhong0/rt-thread-qboot#5]
![image](https://user-images.githubusercontent.com/34146874/136908875-80a72ee7-55b8-44f0-9bd1-332832ee185b.png)
您好！

      上图红框中是否要加一个if判断，否则，不管download区是否检验成功，都会qbt_jump_to_app，如果download区没有内容，就是在那里了吧？

**Comment by qiyongzhong0** [comment]
### 不需要，因为没有合法qbt_jump_to_app不会跳转而是直接返回了。
