### ISSUE TITLE
请问QBootPackager有命令行版本?

### ISSUE THREAD

**Issue by dongly** [qiyongzhong0/rt-thread-qboot#7]
想写脚本自动打包.

**Comment by dongly** [comment]
另,若开QBootPackager能开源更好 :-D

**Comment by 209jkjkjk** [comment]
同问，需要命令行版本

**Comment by nicholas-zww** [comment]
请问QBootPackager有linux命令行版本?

**Comment by qiyongzhong0** [comment]
没有linux命令行版本，有windows下的命令行版本。

 
发件人： NikZww
发送时间： 2024-06-14 22:04
收件人： qiyongzhong0/rt-thread-qboot
抄送： 齐永忠; State change
主题： Re: [qiyongzhong0/rt-thread-qboot] 请问QBootPackager有命令行版本? (Issue #7)
请问QBootPackager有linux命令行版本?

**Comment by nicholas-zww** [comment]
> 没有linux命令行版本，有windows下的命令行版本。 发件人： NikZww 发送时间： 2024-06-14 22:04 收件人： qiyongzhong0/rt-thread-qboot 抄送： 齐永忠; State change 主题： Re: [qiyongzhong0/rt-thread-qboot] 请问QBootPackager有命令行版本? (Issue #7) 请问QBootPackager有linux命令行版本? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

可以给一下代码吗？ 
如果不想公开代码，可以给一下pkg跟raw的crc32计算方法吗，谢谢。
我这边自己计算，所有的crc （header, pkg和raw）都跟你的不一样

**Comment by qiyongzhong0** [comment]
CRC32多项式：

信息头校验：计算范围从信息头起始到CRC校验之前

固件数据校验：计算范围整个固件数据




可以给一下代码吗？
如果不想公开代码，可以给一下pkg跟raw的crc32计算方法吗，谢谢。
我这边自己计算，所有的crc （header, pkg和raw）都跟你的不一样
