### ISSUE TITLE
调用HAL_RCC_DeInit()后，mcu复位。

### ISSUE THREAD

**Issue by Krislanqx** [qiyongzhong0/rt-thread-qboot#9]
参考链接https://www.armbbs.cn/forum.php?mod=viewthread&tid=115762

根据链接方法，修改调用顺序如下，正常启动，不复位。

    HAL_RCC_DeInit();

    SysTick->CTRL = 0;
    SysTick->LOAD = 0;
    SysTick->VAL = 0;

**Comment by qiyongzhong0** [comment]
已完成优化.
